//
//  ListNewsPresenter.swift
//  VIPHeadLine
//
//  Created by SONG on 2/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNewsPresentationLogic
{
    func presentArticles(response: ListNews.GetArticle.Response)
}

class ListNewsPresenter: ListNewsPresentationLogic
{
    weak var viewController: ListNewsDisplayLogic?
    
    // MARK: presentArticles
    
    func presentArticles(response: ListNews.GetArticle.Response)
    {
        var displayedArticles:[ListNews.GetArticle.ViewModel.DisplayedArticle] = []
        
        for article in response.articles {
            let title = article.title
            let description = article.description
            let displayedArticle = ListNews.GetArticle.ViewModel.DisplayedArticle(title: title, description: description ?? "[Empty]")
            displayedArticles.append(displayedArticle)
        }
        
        let viewModel = ListNews.GetArticle.ViewModel(displayedArticles: displayedArticles)
        viewController?.displayArticles(viewModel: viewModel)
    }
}
