//
//  ListNewsInteractor.swift
//  VIPHeadLine
//
//  Created by SONG on 2/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNewsBusinessLogic
{
    func getArticles(request: ListNews.GetArticle.Request)
}

protocol ListNewsDataStore
{
    var articles: [Article] { get }
}

class ListNewsInteractor: ListNewsBusinessLogic, ListNewsDataStore
{
    var articles: [Article] = []
    var presenter: ListNewsPresentationLogic?
    var worker: ArticlesWorker?

    
    // MARK: getArticles
    
    func getArticles(request: ListNews.GetArticle.Request)
    {
        worker = ArticlesWorker(articlesManager: ArticlesAPI())
        worker?.getArticles { articles in
            self.articles = articles
            let response = ListNews.GetArticle.Response(articles: articles)
            self.presenter?.presentArticles(response: response)
        }
    }
}
