//
//  ListNewsRouter.swift
//  VIPHeadLine
//
//  Created by SONG on 2/11/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//MARK: 화면이동은 이걸로.
import UIKit

@objc protocol ListNewsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ListNewsDataPassing
{
  var dataStore: ListNewsDataStore? { get }
}

class ListNewsRouter: NSObject, ListNewsRoutingLogic, ListNewsDataPassing
{
  weak var viewController: ListNewsViewController?
  var dataStore: ListNewsDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
    
  // MARK: Navigation
  
  //func navigateToSomewhere(source: ListNewsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ListNewsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
